apiVersion: v2
name: external-secrets
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: external-secrets
  version: 1.2.1
  repository: https://charts.external-secrets.io/