apiVersion: v2
name: prometheus-crds
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: prometheus-operator-crds
  version: 24.0.2
  repository: https://prometheus-community.github.io/helm-charts
