apiVersion: v2
name: intel-device-plugins-gpu
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: intel-device-plugins-gpu
  version: 0.34.1
  repository: https://intel.github.io/helm-charts/
