app-template:
  image:
    repository: ghcr.io/onedr0p/radarr
    tag: 4.2.4.6635
    pullPolicy: IfNotPresent

  env:
    READARR__PORT: &port 80
    READARR__LOG_LEVEL: info

  podAnnotations:
    backup.velero.io/backup-volumes-excludes: jellyfin-cache,jellyfin-tv,jellyfin-movies,jellyfin-transcodes

  service:
    main:
      ports:
        http:
          port: *port

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "prod-issuer"
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8"
      hosts:
        - host: readarr.k8s.tylercash.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: readarr-letsencrypt-certificate
          hosts:
            - readarr.k8s.tylercash.dev

  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "Always"

  persistence:
    config:
      enabled: true
      storageClass: ceph-block
      size: 5Gi
    share:
      enabled: true
      type: pvc
      existingClaim: calibre-media

  resources:
    limits:
      cpu: 500m
      memory: 606Mi
    requests:
      cpu: 400m
      memory: 500Mi
