apiVersion: v2
name: authentik
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: authentik
  version: 2024.8.3
  repository: https://charts.goauthentik.io/
- name: redis
  version: 20.2.1
  repository: oci://registry-1.docker.io/bitnamicharts

